name: flutter app CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  android-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
         channel: master
      # - run: flutter doctor

      - run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ./build/app/outputs/flutter-apk/app-release.apk
