name: base64

on:
  workflow_dispatch:

jobs:
  base64:
    runs-on: ubuntu-latest

    steps:
      - name: base64tofile
        id: base64
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'release.keystore'
          fileDir: './android/app'
          encodedString: ${{ secrets.KEY_STORE }}
          
      - run: cat android/app/release.keystore
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
         flutter-version: 3.0.0
      # - run: flutter doctor

      - run: flutter build apk
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ./build/app/outputs/flutter-apk/app-release.apk
