name: base64

on:
  workflow_dispatch:

jobs:
  base64:
    runs-on: ubuntu-latest

    steps:
      - name: base64tofile
        id: base64
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'release.keystore'
          fileDir: './android/'
          encodedString: ${{ secrets.KEY_STORE }}
      
      - run: echo ${{ steps.base64.outputs.filePath }}
      
      - run: echo "keystorePath=android/release.keystore" > android/signing.properties
      - run: echo "keystorePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/signing.properties
      - run: echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/signing.properties
      - run: echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/signing.properties
          
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
         channel: master
      # - run: flutter doctor

      - run: flutter build apk
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ./build/app/outputs/flutter-apk/app-release.apk
