name: base64

on:
  workflow_dispatch:

jobs:
  base64:
    runs-on: ubuntu-latest

    steps:
      - name: base64tofile
        id: base64
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'arc.keystore'
          fileDir: './android/'
          encodedString: ${{ secrets.KEY_STORE }}
      
      - run: echo ${{ steps.base64.outputs.filePath }}
          
      - name: upload app
        uses: actions/upload-artifact@v2
        with:
          name: arc.keystore
          path: /Users/runner/work/testCI/testCI/android/arc.keystore
          retention-days: 1
