name: upload aliyun

on:
  pull_request:
    branches: [ ci ]
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    name: Build and Deploy to OSS
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Download
        run: Invoke-WebRequest https://curl.se/windows/dl-8.6.0_3/curl-8.6.0_3-win64-mingw.zip -OutFile curl.zip
      
      - name: Extract
        run: Expand-Archive curl.zip
      
      - name: Config OSS
        uses: yizhoumo/setup-ossutil@v2
        with:
          ## The version to download and use, or 'latest' for the latest version.
          ossutil-version: '1.7.18'
      
          # The following parameters are (optionally) used to config the credential.
          ## The endpoint of the region in which the bucket is located.
          endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          ## The AccessKey ID of the credential.
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ## The AccessKey Secret of the credential.
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          ## The STS Token of the credential. Only required for temporary access.
          ## sts-token: ${{ secrets.OSS_STS_TOKEN }}
      - name: Upload to Aliyun
        run: |
          ossutil sign oss://arcsite-x-dev-app-package/v1/curl-8.6.0_3-win64-mingw/README.txt --timeout 3600 --loglevel=debug
    
         # ossutil cp -f --recursive ./curl oss://arcsite-x-dev-app-package/v1
        # echo "DOWNLOAD_URL=$(ossutil sign oss://arcsite-x-dev-app-package/v1/curl-8.6.0_3-win64-mingw/README.txt --timeout 3600)" >> $GITHUB_ENV
        # echo "${{ env.DOWNLOAD_URL }}"
        
      - id: generate-url
        name: Generate Url
        shell: pwsh
        run: |
          Set-Variable -Name TheUrl -Value $(ossutil sign oss://arcsite-x-dev-app-package/v1/curl-8.6.0_3-win64-mingw/README.txt --timeout 3600)
          "download-url=$TheUrl" >> $env:GITHUB_OUTPUT
      - name: print url
        shell: pwsh
        run: |
          Write-Output "download url is: ${{ steps.generate-url.outputs.download-url }}"
