name: tag

on:
  workflow_dispatch:
    inputs:
      appVersion:
        type: string
        default: '1.1.0'
        description: 'app version'

jobs:
  base64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: git tag "v${{ inputs.appVersion }}"
      - run: git push --tags
