name: test ndk
on:
  workflow_dispatch:
  
jobs:
  test-ndk:
    runs-on: macos-latest
    steps:
      - run: ls -a /Users/runner/Library/Android/sdk/ndk/25.2.9519653
      - run: wget https://dl.google.com/android/repository/android-ndk-r25b-darwin.zip
      - run: unzip android-ndk-r25b-darwin.zip -d /Users/runner/Library/Android/sdk/ndk/25.1.8937393
      - run: ls -a /Users/runner/Library/Android/sdk/ndk/25.1.8937393
