name: upload aliyun

on:
  pull_request:
    branches: [ ci ]
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    name: Build and Deploy to OSS
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Download
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
      
      - name: Extract
        run: Expand-Archive ngrok.zip
      
      - name: upload to aliyun
      - uses: yizhoumo/setup-ossutil@v2
        with:
          ## The version to download and use, or 'latest' for the latest version.
          ossutil-version: '1.7.18'
      
          # The following parameters are (optionally) used to config the credential.
          ## The endpoint of the region in which the bucket is located.
          endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          ## The AccessKey ID of the credential.
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ## The AccessKey Secret of the credential.
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          ## The STS Token of the credential. Only required for temporary access.
          ## sts-token: ${{ secrets.OSS_STS_TOKEN }}

      - run: ossutil64.exe cp -f ./ngrok oss://arcsite-x-dev-app-package

     #   uses: saltbo/uptoc@master
     #   with:
     #     driver: oss
     #     region: ALIYUN_OSS_ENDPOINT
     #     bucket: ALIYUN_OSS_BUCKET
     #     exclude: .cache,test
     #     dist: "./ngrok"
     #   env:
     #     UPTOC_UPLOADER_AK: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
     #     UPTOC_UPLOADER_SK: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      
     #  - uses: Menci/upload-to-oss@beta-v3
     #    with:
     #      # Use Access Key
     #      access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
     #      access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
     #      # Or use STS Token
     #      # security-token: ${{ secrets.ALIYUN_SECURITY_TOKEN }}

     #      bucket: ${{ secrets.ALIYUN_OSS_BUCKET }}
     #      endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}

     #      # Upload the built website files in "dist" directory to remote "my-website/" prefix
     #     local-path: "./ngrok"
     #     remote-path: my-remote-test-path
