name: flutter app CI

on:
  pull_request:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
         channel: master
      # - run: flutter doctor

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter pub run msix:create

      - uses: actions/upload-artifact@v2
        with:
          name: msix
          path: ./build/windows/runner/Release/test_ci.msix
