# This is a basic workflow to help you get started with Actions

name: flutter app CI

# Controls when the action will run. 
on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windows-build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
         channel: master
      # - run: flutter doctor

      - run: flutter config --enable-windows-desktop
      - run: flutter build windows

      - uses: actions/upload-artifact@v2
        with:
          name: exe
          path: ./build/windows/runner/Release
